mba<-read.csv("C:/Users/Ameesha/Desktop/initial.csv")
View(mba)
fix(mba)
View(mba)
mba$Fees[is.na(mba$Fees)]<-round(mean(mba$Fees,na.rm=TRUE))
View(mba)
install.packages(("VIM"))
install.packages("mvnmle")
library(mvnmle)
library(VIM)
a<-subset(mba,select=c("Ranking","CAT_Cutoff","AvgSal","companies","Placement"))
summary(a)
cov(a)
mlest(a)
imputed.cov.a<-mlest(a)$sigmahat
summary(a)
imputed.cov.a
a
data(a)
summary(imputed.cov.a)
imputed.a<-irmi(a)
summary(imputed.a)
imputed.a
a
install.packages("mice")
library(mice)
imputed_data = complete( mice( a ))
imputed_data
mba$CAT_Cutoff=imputed_data$CAT_Cutoff
View(mba)
str(mba)
mba$sexratio<-mba$boys/mba$girls
View(mba)
fix(mba)
cor(mba[c("Ranking","CAT_Cutoff","AvgSal","Fees","MDPs","faculty","companies","Placement","internationalfaculty","studentexchange","guestspeakers","sexratio")])
library(psych)
pairs.panels(mba[c("Ranking","CAT_Cutoff","AvgSal","Fees","MDPs","faculty","companies","Placement","internationalfaculty","studentexchange","guestspeakers","sexratio")])
View(mba)
analysis<-lm(Ranking~CAT_Cutoff+AvgSal+Fees+MDPs+faculty+companies+Placement+internationalfaculty+studentexchange+guestspeakers+sexratio,data=mba)
analysis
summary(analysis)
plot(analysis)
mba2<-subset(mba,select=c("CAT_Cutoff","AvgSal","MDPs","faculty","companies","Placement","internationalfaculty","studentexchange","guestspeakers","sexratio"))
View(mba2)
View(mba)
mins <- apply(mba2, 2, min)
maxs <- apply(mba2, 2, max)
scaled.mba <- scale(mba2, center = mins, scale = maxs - mins)
View(scaled.mba)
categorize<-data.frame(sno=1:20)
weight<-c(2,1,1)
categorize$placements<-apply(subset(scaled.mba,select=c("AvgSal","companies","Placement")), 1, function(d) weighted.mean(d, weight))
weight<-c(3,1)
categorize$personality_development<-apply(subset(scaled.mba,select=c("studentexchange","sexratio")), 1, function(d) weighted.mean(d, weight))
View(categorize)
weight<-c(3,2,1)
categorize$exposure<-apply(subset(scaled.mba,select=c("studentexchange","internationalfaculty","guestspeakers")), 1, function(d) weighted.mean(d, weight))
weight<-c(1,1,1)
categorize$academics<-apply(subset(scaled.mba,select=c("MDPs","faculty","internationalfaculty")), 1, function(d) weighted.mean(d, weight))
categorize<-subset(categorize,select=-sno)
categorize$quality<-rowSums(categorize)
View(categorize)
categorize<-data.frame(mba$Name,categorize,mba$Fees)
View(categorize)
fix(categorize)
View(categorize)
attach(categorize)
plot(Fees,quality)
cov(Fees,quality)
cor(quality,Fees)
categorize$VFM<-Fees/quality
View(categorize)
categorize$Ranking<-mba$Ranking
View(categorize)
library(cluster)
mba.dist = dist(scaled.mba)
mba.hclust = hclust(mba.dist)
groups.5 = cutree(mba.hclust,5)
sapply(unique(groups.5),function(g)mba$Name[groups.5 == g])
aggregate(scaled.mba,list(groups.5),median)
aggregate(mba,list(groups.5),median)
aggregate(mba[,-c(1,2)],list(groups.5),median)
mba.pam = pam(mba.dist,5)
table(groups.5,mba.pam$clustering)
mba$Name[groups.5 != mba.pam$clustering]
mba$Name[mba.pam$id.med]
mba$Name[mba.pam$id.med]
plot(mba.pam)
plot(silhouette(cutree(mba.hclust,3),mba.dist))
plot(silhouette(cutree(mba.hclust,2),mba.dist))
View(mba)
write.csv(mba, 'test2.csv')
write.csv(mba2, 'mba2.csv')
write.csv(categorize, 'categorize.csv')
write.csv(scaled.mba, 'scaled.csv')
 
